# Generated by Django 5.2.14 on 2026-05-25 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSaber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Área do Saber',
                'verbose_name_plural': 'Áreas do Saber',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco_base_internacional', models.CharField(max_length=100, verbose_name='Preço base internacional')),
                ('unidade_medida', models.CharField(max_length=100, verbose_name='Unidade de medida')),
            ],
            options={
                'verbose_name': 'Commodity',
                'verbose_name_plural': 'Commodities',
            },
        ),
        migrations.CreateModel(
            name='FonteInformacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('url', models.CharField(max_length=100, verbose_name='URL de referência')),
                ('score', models.CharField(max_length=100, verbose_name='Score de credibilidade')),
            ],
            options={
                'verbose_name': 'Fonte de Informação',
                'verbose_name_plural': 'Fontes de Informação',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('regiao', models.CharField(max_length=100, verbose_name='Região')),
                ('continente', models.CharField(max_length=100, verbose_name='Continente')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='EventoGeopolitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('data', models.CharField(max_length=100, verbose_name='Data de início')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de evento')),
                ('areasaber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areasaber', verbose_name='Área do saber')),
            ],
            options={
                'verbose_name': 'Evento Geopolítico',
                'verbose_name_plural': 'Eventos Geopolíticos',
            },
        ),
        migrations.CreateModel(
            name='ImpactoEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição do impacto')),
                ('prazo', models.CharField(max_length=100, verbose_name='Prazo estimado')),
                ('eventogeopolitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventogeopolitico', verbose_name='Evento geopolítico')),
            ],
            options={
                'verbose_name': 'Impacto Econômico',
                'verbose_name_plural': 'Impactos Econômicos',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('site', models.CharField(max_length=100, verbose_name='Site oficial')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de instituição')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.localizacao', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='IndicadorInflacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_percentual', models.CharField(max_length=100, verbose_name='Valor percentual')),
                ('data', models.CharField(max_length=100, verbose_name='Data de referência')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commodity', verbose_name='Commodity')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.localizacao', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Indicador de Inflação',
                'verbose_name_plural': 'Indicadores de Inflação',
            },
        ),
        migrations.CreateModel(
            name='FluxoMigratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=100, verbose_name='Quantidade estimada')),
                ('justificativa', models.CharField(max_length=100, verbose_name='Justificativa da crise')),
                ('locdestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='app.localizacao', verbose_name='Localização de destino')),
                ('locorigem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='app.localizacao', verbose_name='Localização de origem')),
            ],
            options={
                'verbose_name': 'Fluxo Migratório',
                'verbose_name_plural': 'Fluxos Migratórios',
            },
        ),
        migrations.CreateModel(
            name='NexoCausal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explicacao', models.CharField(max_length=100, verbose_name='Explicação didática')),
                ('estrutura', models.CharField(max_length=100, verbose_name='Estrutura de análise')),
                ('eventogeopolitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventogeopolitico', verbose_name='Evento geopolítico')),
                ('impactoeconomico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.impactoeconomico', verbose_name='Impacto económico')),
            ],
            options={
                'verbose_name': 'Nexo Causal',
                'verbose_name_plural': 'Nexos Causais',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=100, verbose_name='CPF')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('datanasc', models.CharField(max_length=100, verbose_name='Data de nascimento')),
                ('nivel', models.CharField(max_length=100, verbose_name='Nível de acesso')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.localizacao', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='LogAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=100, verbose_name='Data')),
                ('hora', models.CharField(max_length=100, verbose_name='Hora')),
                ('acao', models.CharField(max_length=100, verbose_name='Ação realizada')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Log de Atualização',
                'verbose_name_plural': 'Logs de Atualização',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100, verbose_name='Texto')),
                ('data', models.CharField(max_length=100, verbose_name='Data')),
                ('hora', models.CharField(max_length=100, verbose_name='Hora')),
                ('eventogeopolitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventogeopolitico', verbose_name='Evento geopolítico')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
        migrations.CreateModel(
            name='RelatorioPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do painel')),
                ('data', models.CharField(max_length=100, verbose_name='Data de geração')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.localizacao', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Relatório por País',
                'verbose_name_plural': 'Relatórios por País',
            },
        ),
        migrations.CreateModel(
            name='RotaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_hub', models.CharField(max_length=100, verbose_name='Nome do hub')),
                ('status', models.CharField(max_length=100, verbose_name='Status operacional')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.localizacao', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Rota Comercial',
                'verbose_name_plural': 'Rotas Comerciais',
            },
        ),
    ]
