# Generated by Django 5.2.14 on 2026-05-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactoeconomico',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição do impacto'),
        ),
        migrations.AlterField(
            model_name='nexocausal',
            name='explicacao',
            field=models.TextField(max_length=500, verbose_name='Explicação didática'),
        ),
    ]
